set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')

set viminfofile=$XDG_STATE_HOME/vim/viminfo

let data_dir = $XDG_CONFIG_HOME.'/vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
    silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin(data_dir . '/plugged')
Plug 'catppuccin/vim', { 'as': 'catppuccin' }

Plug 'mboughaba/i3config.vim'
Plug 'rust-lang/rust.vim'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'imsnif/kdl.vim'
Plug 'elkowar/yuck.vim'
Plug 'Fymyte/rasi.vim'

Plug 'junegunn/goyo.vim'
Plug 'kshenoy/vim-signature'
Plug 'francoiscabrol/ranger.vim'
Plug 'tpope/vim-speeddating'
call plug#end()

set nocompatible
set encoding=utf-8
set termguicolors
set t_Co=256
colorscheme catppuccin_mocha

set expandtab shiftwidth=4 tabstop=4

set cc=120
set wildmode=longest,list,full path+=**
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
set number relativenumber
set list
set listchars=tab:→\ ,trail:·
set hlsearch ignorecase smartcase

syntax enable
filetype plugin indent on

let g:netrw_banner=0
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_liststyle=3
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'
let g:netrw_keepdir = 0
let g:ranger_map_keys = 0
let g:ranger_replace_netrw = 1

autocmd FileType make setlocal noexpandtab
command! MakeTags !ctags -R .

map j gj
map k gk

" Copy from desktop ("+ requires gvim installed)
vnoremap <c-c> "+y

let mapleader = " "
nnoremap <leader>1 :1tabnext<CR>
nnoremap <leader>2 :2tabnext<CR>
nnoremap <leader>3 :3tabnext<CR>
nnoremap <leader>4 :4tabnext<CR>
nnoremap <leader>5 :5tabnext<CR>
nnoremap <leader>6 :6tabnext<CR>
nnoremap <leader>7 :7tabnext<CR>
nnoremap <leader>8 :8tabnext<CR>
nnoremap <leader>9 :9tabnext<CR>
nnoremap <leader>o :setlocal spell! spelllang=en_us<cr>
nnoremap <leader>g :Goyo<cr>
nnoremap <leader>h :bnext<cr>
nnoremap <leader>l :bprevious<cr>
nnoremap <leader>e :enew<cr>
nnoremap <leader>x :bd<cr>
nnoremap <leader>b :Lex<cr>:vertical resize 30 <cr>
nnoremap <leader>m a···<esc>3h
nnoremap <leader>n :set number! relativenumber!<cr>
nnoremap <leader>c :tabedit ~/.config/vim/vimrc<cr>
nnoremap <leader>w :!rm ~/.local/state/vim/swap/*.swp
nnoremap <leader>f :RangerWorkingDirectory<cr>
nnoremap <leader>t :RangerWorkingDirectoryNewTab<cr>

nnoremap <tab><tab> <esc>h/···<enter>"_c3l
inoremap <tab><tab> <esc>h/···<enter>"_c3l
vnoremap <tab><tab> <esc>h/···<enter>"_c3l

source ~/.config/vim/snippets/rust.snippets
source ~/.config/vim/snippets/cpp.snippets
source ~/.config/vim/snippets/bash.snippets
source ~/.config/vim/snippets/tex.snippets
autocmd BufNewFile,BufRead *.snippets :set filetype=vim

inoremap <c-l> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

