export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_TEMPLATES_DIR="$HOME/templates"
export XDG_DOCUMENTS_DIR="$HOME/documents"
export XDG_MUSIC_DIR="$HOME/music"
export XDG_PICTURES_DIR="$HOME/images"
export XDG_VIDEOS_DIR="$HOME/videos"

export MY_DEVELOPMENT_DIR="$HOME/dev"
export MY_WALLPAPERS_DIR="$HOME/wallpapers"

export USERNAME="Treefonov Andrey"
export NICKNAME="Reefufui"

alias ls='exa --icons --all'
alias la='exa --icons --all -l'
alias tree='exa --icons --tree'
alias tree2='exa --icons --tree --level=2'
alias tree3='exa --icons --tree --level=3'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gd='git diff'
alias gs='git status'
alias wget=wget --hsts-file="$XDG_DATA_HOME/wget-hsts"

export HISTFILE="${XDG_STATE_HOME}"/bash/history

export VISUAL=vim
export EDITOR=vim
export MYVIMRC=$XDG_CONFIG_HOME/vim/vimrc
export VIMINIT='source $MYVIMRC'

export STARSHIP_CONFIG=$XDG_CONFIG_HOME/starship/config.toml
export STARSHIP_CACHE=$XDG_CACHE_HOME/starship/cache

export CARGO_HOME="$XDG_DATA_HOME"/cargo
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export XCURSOR_PATH=/usr/share/icons:${XDG_DATA_HOME}/icons
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter
export LESSHISTFILE="$XDG_STATE_HOME"/less/history
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup

export VULKAN_SDK=/opt/vulkan/1.2.189.0/x86_64
export LD_LIBRARY_PATH=$VULKAN_SDK/lib:$LD_LIBRARY_PATH
export VK_LAYER_PATH=$VULKAN_SDK/etc/vulkan/explicit_layer.d

export PYTHONPATH=/usr/bin/python

export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.scripts:$PATH
export PATH=$VULKAN_SDK/bin:$PATH
export PATH=$CARGO_HOME/bin:$PATH

eval "$(starship init bash)"
eval "$(zoxide init bash)"

